### ISSUE TITLE
Compatibility with Turborepo

### ISSUE THREAD

**Issue by balcieren** [hyoban/tailwindcss-icons#32]
Hi,

I tried to use with Turborepo, but icons did not appear on the website.
Additionally, I use turborepo with npm workspace.
I think, it cannot find the icon package from node_modules so the problem is caused by this reason.
Or am I wrong? Am I doing something wrong?

**Comment by hyoban** [comment]
Can you provide a minimal reproduction?

**Comment by balcieren** [comment]
> Can you provide a minimal reproduction?

Hi, My problem has solved. The problem was about with css file. I was importing my tailwind css file from the outside package. Then I added one more time global css to the web app. It worked successfully.

**Comment by hyoban** [comment]
Glad to hear it, closing this issue as it's resolved
