### ISSUE TITLE
escaping the ";" character in path 

### ISSUE THREAD

**Issue by peter-emad99** [hyoban/tailwindcss-icons#36]
i have wired problem ...i try to use an animated svg as custom icon ..it works fine but if i but any animation attributes that requires to seprate the values with semicolon ";'(like "values" in given svg) ...i break all the styles of the app .. i tried to but the url encoding value of semicolon "%3B" but it aslo didn't work because the final result of the data uri svg is "%253b" which replacing the % with it url encoding value 
i know this is not a big problem ..but if any one can help ??
 
```<circle fill="currentColor" stroke="none" cx="25" cy="10" r="6"><animate attributeName="opacity" dur="1s" values="0;1;0" from="0" to="1" repeatCount="indefinite" begin="0.1"/></circle>```

**Comment by hyoban** [comment]
Sorry, this is a bug, I will fix it ASAP
