### ISSUE TITLE
No longer able to discover any icon when using `@iconify/json`

### ISSUE THREAD

**Issue by benjamincanac** [hyoban/tailwindcss-icons#38]
Since https://github.com/egoist/tailwindcss-icons/releases/tag/v1.4.0 release and #29 or maybe https://github.com/egoist/tailwindcss-icons/commit/b53dde99c57d8f0735a851c6065d4313a13cbdc5, I'm not able to discover any icon when using the `@iconify/json` package.

It was done previously by passing `all` to `getIconCollections`.

I've also tried to use the `dynamicIconsPlugin`, but I don't really want to use such syntax `<span class="i-[mdi-light--home]"></span>` as mentioned [here](https://github.com/egoist/tailwindcss-icons/commit/b53dde99c57d8f0735a851c6065d4313a13cbdc5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R112) as it would cause a breaking change.

**Comment by hyoban** [comment]
Sorry, I forgot to mark this as a breaking change. 

Maybe i should revert and still support `all` options? But this also seems to have an impact on the auto-completion of the tailwindcss vscode plugin. Or there is no problem when using it with `UIcon`?
