### ISSUE TITLE
Using `:` as separator

### ISSUE THREAD

**Issue by zcf0508** [hyoban/tailwindcss-icons#39]
I check the source code and find that the dynamic plugin support using `:` as separator.

https://github.com/egoist/tailwindcss-icons/blob/main/src/dynamic.ts#L23

```ts
const nameParts = icon.split(/--|\:/)
```

But when I write a class like `i-[mdi:home]` or `hover:i-[mdi:home]`, the plugin does not generate the css code. And I change the class to `i-[mdi--home]` and `hover:i-[mdi--home]`, the plugin works fine.

**Comment by hyoban** [comment]
Sorry, you cannot use `:` as delimiter, because `i-[mdi:home]` is not a valid selector.

You can try it at https://www.cssportal.com/css-validator
