### ISSUE TITLE
Support hover with correct size

### ISSUE THREAD

**Issue by atinux** [hyoban/tailwindcss-icons#4]
Reproduction: https://stackblitz.com/edit/github-dpc8s6?file=tailwind.config.js,app.vue,nuxt.config.ts

```html
<template>
  <div>
    <span class="i-mdi-home hover:i-uil-dice-one h-12 w-12 text-orange-500"></span>
  </div>
</template>
```

**Comment by egoist** [comment]
I think it's the same way in unocss, `hover:i-uil-dice-one` have a `width:1em`&`height:1em` that will override `h-12 w-12`, I usually use `text-2xl` to set icon size instead.

**Comment by atinux** [comment]
Added an example on https://tailwindcss.nuxtjs.org/examples/tailwind-icons :)
