### ISSUE TITLE
Using icons from custom package under different scope (not @iconify-json)

### ISSUE THREAD

**Issue by adjabaev** [hyoban/tailwindcss-icons#41]
Hello,

Is it be possible to use this package using the @iconify-json scope aswell as some (one) custom scope?

Thank you in advance!

**Comment by hyoban** [comment]
Can you show an example?

**Comment by adjabaev** [comment]
Let's imagine I would like to use
@iconify-json/fa6-brands
aswell as
@test/custom-icons (hosted on personal server)

right now it has to be @iconify-json/{collection_name} which makes it not possible

the icons are tied to one of my project so I would like to keep them hosted on my server, but npm won't allow me to host packages using @iconify-json as it cannot handle two repositories for one scope

**Comment by hyoban** [comment]
This should not be supported. May be you can try `pnpm add <any-alias-name>@npm:package-name`? or load your package manually to custom iconset

**Comment by adjabaev** [comment]
I didn't know the alias feature existed, thank you very much for your help it works 💯 !
