### ISSUE TITLE
Tailwind v4 support

### ISSUE THREAD

**Issue by vdawg-git** [hyoban/tailwindcss-icons#52]
V4 is in beta, but the Tailwind team said that there wont be any breaking changes anymore.

So supporting this would be very cool :D

**Comment by Barbapapazes** [comment]
Hey 👋,

Have you try this plugin with Tailwind 4? It does not work?

**Comment by Barbapapazes** [comment]
I try and using this `@config "../tailwind.config.ts";` in your main css file and everything works fine!

**Comment by hyoban** [comment]
Yes, you can still make it work by importing the configuration file, I don't know yet how to allow args to be passed to the plugin in the CSS configuration

**Comment by vdawg-git** [comment]
Same, the Tailwind docs dont explain how to configure plugins via the css config

Edit: But it works, so I am closing the issue :)

**Comment by Barbapapazes** [comment]
> Same, the Tailwind docs dont explain how to configure plugins via the css config
> 
> Edit: But it works, so I am closing the issue :)

It is explained here: https://tailwindcss.com/docs/v4-beta#using-legacy-configuration-files

**Comment by vdawg-git** [comment]
@Barbapapazes I think you misread what I wrote. This is explains how to use the legacy config format with the new one, not how to configure plugins with the new css config

**Comment by Barbapapazes** [comment]
Sorry, my message was too short but it's possible to add a plugin using the CSS config (https://tailwindcss.com/docs/v4-beta#using-plugins) but I didn't find a way to pass a configuration to the plugin so the old JS config file is, as far as I know, the only way.
